name: CI

permissions:
  pull-requests: write

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
          cache: pipenv
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install Dependencies
        run: |
          pipenv install --dev
      - name: Download GeoIp2 database
        run: |
          cd .geoip && ./download-database.sh
      - name: Run Lint
        run: |
          pipenv run lint
      - name: Run Type Checker
        run: |
          pipenv run check-typing
      - name: Run Tests with Coverage
        run: |
          pipenv run coverage
          pipenv run coverage-xml
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          thresholds: '80 95'
          output: both
      - name: Add Coverage Report as PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
