name: CI

on:
  - push
  - pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.1
          cache: pipenv
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install Dependencies
        run: |
          pipenv install --dev
      - name: Run Lint
        run: |
          pipenv run lint
      - name: Run Type Checker
        run: |
          pipenv run type-checker
      - name: Run Tests with coverage
        run: |
          pipenv run coverage
          pipenv run coverage-xml
      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          thresholds: '80 95'
